---
galaxy_info:
  author: O-RAN-SC IT/Dep
  description: Ansible role for uninstalling SMO (Service Management and Orchestration) components
  company: O-RAN Software Community
  license: Apache-2.0
  min_ansible_version: "2.9"
  
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  
  galaxy_tags:
    - o-ran
    - smo
    - kubernetes
    - helm
    - onap
    - nonrtric
    - uninstall
    - cleanup

dependencies: []
