---
- name: Remove old Docker installations
  apt:
    name:
      - docker
      - docker-engine
      - docker.io
      - containerd
      - runc
    state: absent
  when: ansible_os_family == "Debian"

- name: Remove old Docker installations (RedHat)
  yum:
    name:
      - docker
      - docker-client
      - docker-client-latest
      - docker-common
      - docker-latest
      - docker-latest-logrotate
      - docker-logrotate
      - docker-engine
    state: absent
  when: ansible_os_family == "RedHat"

- name: Add Docker GPG key (Ubuntu/Debian)
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository (Ubuntu/Debian)
  apt_repository:
    repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
    state: present
  when: ansible_os_family == "Debian"

- name: Add Docker repository (RedHat/CentOS)
  yum_repository:
    name: docker-ce
    description: Docker CE Repository
    baseurl: "https://download.docker.com/linux/centos/$releasever/$basearch/stable"
    gpgcheck: yes
    gpgkey: https://download.docker.com/linux/centos/gpg
  when: ansible_os_family == "RedHat"

- name: Install Docker packages (Ubuntu/Debian)
  apt:
    name:
      - "docker-ce{% if docker_version != '' %}={{ docker_version }}{% endif %}"
      - "docker-ce-cli{% if docker_version != '' %}={{ docker_version }}{% endif %}"
      - containerd.io
      - docker-compose-plugin
    state: present
    update_cache: yes
  when: ansible_os_family == "Debian"

- name: Install Docker packages (RedHat/CentOS)
  yum:
    name:
      - "docker-ce{% if docker_version != '' %}-{{ docker_version }}{% endif %}"
      - "docker-ce-cli{% if docker_version != '' %}-{{ docker_version }}{% endif %}"
      - containerd.io
    state: present
  when: ansible_os_family == "RedHat"

- name: Create Docker configuration directory
  file:
    path: /etc/docker
    state: directory
    mode: '0755'

- name: Configure Docker daemon
  template:
    src: daemon.json.j2
    dest: /etc/docker/daemon.json
    mode: '0644'
  notify: restart docker

- name: Create systemd drop-in directory for Docker
  file:
    path: /etc/systemd/system/docker.service.d
    state: directory
    mode: '0755'

- name: Add user to docker group
  user:
    name: "{{ target_user }}"
    groups: docker
    append: yes
  when: target_user is defined

- name: Start and enable Docker service
  systemd:
    name: docker
    state: started
    enabled: yes
    daemon_reload: yes

- name: Configure insecure registry (if enabled)
  block:
    - name: Create registry certificate directory
      file:
        path: "/etc/docker/certs.d/{{ docker_registry.host }}:{{ docker_registry.port }}"
        state: directory
        mode: '0755'

    - name: Mark registry as insecure
      copy:
        dest: "/etc/docker/certs.d/{{ docker_registry.host }}:{{ docker_registry.port }}/ca.crt"
        content: ""
        mode: '0644'
      notify: restart docker
  when: docker_registry.enabled | bool and docker_registry.insecure | bool

- name: Login to private registry
  docker_login:
    registry_url: "{{ docker_registry.host }}:{{ docker_registry.port }}"
    username: "{{ docker_registry.username }}"
    password: "{{ docker_registry.password }}"
  when: 
    - docker_registry.enabled | bool
    - docker_registry.username != ""
    - docker_registry.password != ""
